// Databricks notebook source
//Join green and yellow at needed granularity for each materialized view

// COMMAND ----------

// MAGIC %sql
// MAGIC --All trips
// MAGIC select * from 
// MAGIC   (
// MAGIC   select taxi_type,
// MAGIC     cast(vendor_id as string) as vendor_id,
// MAGIC     pickup_datetime,
// MAGIC     dropoff_datetime,
// MAGIC     store_and_fwd_flag,
// MAGIC     rate_code_id,
// MAGIC     pickup_location_id,
// MAGIC     dropoff_location_id,
// MAGIC     pickup_longitude,
// MAGIC     pickup_latitude,
// MAGIC     dropoff_longitude,
// MAGIC     dropoff_latitude,
// MAGIC     passenger_count,
// MAGIC     trip_distance,
// MAGIC     fare_amount,
// MAGIC     extra,
// MAGIC     mta_tax,
// MAGIC     tip_amount,
// MAGIC     tolls_amount,
// MAGIC     ehail_fee,
// MAGIC     improvement_surcharge,
// MAGIC     total_amount,
// MAGIC     cast(payment_type as string) as payment_type,
// MAGIC     trip_type,
// MAGIC     trip_year,
// MAGIC     trip_month,
// MAGIC     vendor_abbreviation,
// MAGIC     vendor_description,
// MAGIC     trip_type_description,
// MAGIC     month_name_short,
// MAGIC     month_name_full,
// MAGIC     payment_type_description,
// MAGIC     rate_code_description,
// MAGIC     pickup_borough,
// MAGIC     pickup_zone,
// MAGIC     pickup_service_zone,
// MAGIC     dropoff_borough,
// MAGIC     dropoff_zone,
// MAGIC     dropoff_service_zone,
// MAGIC     pickup_year,
// MAGIC     pickup_month,
// MAGIC     pickup_day,
// MAGIC     pickup_hour,
// MAGIC     pickup_minute,
// MAGIC     pickup_second,
// MAGIC     dropoff_year,
// MAGIC     dropoff_month,
// MAGIC     dropoff_day,
// MAGIC     dropoff_hour,
// MAGIC     dropoff_minute,
// MAGIC     dropoff_second
// MAGIC   from nyc_db.trips_green_transformed_prq
// MAGIC 
// MAGIC   union all
// MAGIC 
// MAGIC   select taxi_type,
// MAGIC     vendor_id,
// MAGIC     pickup_datetime,
// MAGIC     dropoff_datetime,
// MAGIC     store_and_fwd_flag,
// MAGIC     rate_code_id,
// MAGIC     pickup_location_id,
// MAGIC     dropoff_location_id,
// MAGIC     pickup_longitude,
// MAGIC     pickup_latitude,
// MAGIC     dropoff_longitude,
// MAGIC     dropoff_latitude,
// MAGIC     passenger_count,
// MAGIC     trip_distance,
// MAGIC     fare_amount,
// MAGIC     extra,
// MAGIC     mta_tax,
// MAGIC     tip_amount,
// MAGIC     tolls_amount,
// MAGIC     null as ehail_fee,
// MAGIC     improvement_surcharge,
// MAGIC     total_amount,
// MAGIC     payment_type,
// MAGIC     null as trip_type,
// MAGIC     trip_year,
// MAGIC     trip_month,
// MAGIC     vendor_abbreviation,
// MAGIC     vendor_description,
// MAGIC     null as trip_type_description,
// MAGIC     month_name_short,
// MAGIC     month_name_full,
// MAGIC     payment_type_description,
// MAGIC     rate_code_description,
// MAGIC     pickup_borough,
// MAGIC     pickup_zone,
// MAGIC     pickup_service_zone,
// MAGIC     dropoff_borough,
// MAGIC     dropoff_zone,
// MAGIC     dropoff_service_zone,
// MAGIC     pickup_year,
// MAGIC     pickup_month,
// MAGIC     pickup_day,
// MAGIC     pickup_hour,
// MAGIC     pickup_minute,
// MAGIC     pickup_second,
// MAGIC     dropoff_year,
// MAGIC     dropoff_month,
// MAGIC     dropoff_day,
// MAGIC     dropoff_hour,
// MAGIC     dropoff_minute,
// MAGIC     dropoff_second
// MAGIC   from nyc_db.trips_yellow_transformed_prq
// MAGIC   ) a

// COMMAND ----------

